version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  hello:
    lang: go
    handler: ./hello
    image: hello:latest
  goto:
    lang: golang-middleware
    handler: ./goto
    image: goto:latest
    secrets:
      - my-secrets
  plusone:
    lang: golang-middleware
    handler: ./plusone
    image: plusone:latest
